build:
  version: "1.0"
accounts:
  message: "Welcome to LGBank Default Cards APIs"
  contactDetails:
    name: "PhamTranDuc-default"
    email: "phamtranduc@gmail.com"
  onCallSupport:
    - "(+86)2293627"

