build:
  version: "2.0"
accounts:
  message: "Welcome to LGBank Prod Loans APIs"
  contactDetails:
    name: "PhamTranDuc-prod"
    email: "phamtranducprod@gmail.com"
  onCallSupport:
    - "(+86)2293627"
