
server:
 port: 9000
spring:
 datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password: ''
 h2:
   console:
    enabled: true
 jpa:
   database-platform: org.hibernate.dialect.H2Dialect
   hibernate:
    ddl-auto: update
   show-sql: true
 config:
   import:
     - "application_qa.yml"
     - "application_prod.yml"
   profiles:
     active:
       - "prod"
build:
  version: "1.0"
accounts:
  message: "Welcome to LGBank Default Cards APIs"
  contactDetails:
    name: "PhamTranDuc-default"
    email: "phamtranducdefault@gmail.com"
  onCallSupport:
    - "(+86)2293627"


#build:
#  version: "1.0"
#accounts:
#  message: "Welcome to LGBank Default APIs"
#  contactDetails:
#    name: "PhamTranDuc-default"
#    email: "phamtranducdefault@gmail.com"
#  onCallSupport:
#    - "(+86)2293627"

