services:
  network-deploy-service:
    networks:
      - ptd

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m

  client-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/

  eureka-server-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CLOUD_CONFIG_URI: http://configserver:8071
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071/
      SERVER_ADDRESS: 0.0.0.0
