
server:
  port: 8070

spring:
  application:
    name: "eurekaserver"
  config:
    import: "optional:configserver:http://configserver:8071/"

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#  config:
#    import: "optional:configserver:http://localhost:8071/"


